UI issues with large font fix issue#28
Automattic/pocket-casts-android pull request #1412
Opened 2023-09-26 11:25 UTC by neeldoshii

Linked Issue : #28 

## Testing Instructions
1. Change your device font size to large
2. Go to settings -> Then Go to Help and Feedback

## Screenshots or Screencast 
![Screenshot 2023-09-26 at 4 24 14 PM](https://github.com/Automattic/pocket-casts-android/assets/60827173/6e28ef44-e010-4068-bb9b-7916d44f0d62)

## Checklist
- [ ] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [ ] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [ ] I have considered whether it makes sense to add tests for my changes
- [ ] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [ ] Any jetpack compose components I added or changed are covered by compose previews
 
#### I have tested any UI changes...

- [ ] with different themes
- [ ] with a landscape orientation
- [X] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

## Fixed
- [X]  Help & Feedback Screen has a bit of horizontal scroll
- [X] Help & Feedback "Still stuck..." box cuts words in half
- [X] Help & Feedback "Get in touch popup" has buttons outside the popup
- [ ] Not all toolbars reflect the updated font size. 
- [ ]  Profile's Active Account section loses its top and bottom padding
- [ ] Podcast page's folder icon feels a bit crowded against the podcast picture
- [ ] The Choose Folder Color screen's colors crowd the right side of the screen

The tick indicates the fixed rest is not fixed. This PR is partial bug fixes.

2023-10-18 19:55 UTC, mchowning requested changes
Thanks for the contrubution @neeldoshii and sorry it's taken awhile to get it reviewed. 

I left a couple of comments just clarifying why we needed a few changes. I didn't see any issues from those changes, but I just want to understand why we need them (and make sure they are necessary changes).

The only significant issue I noticed is that I'm seeing an extra black bar across the top of the screen that wasn't there before. It looks like something with the padding is off. It's a little hard to see in this screenshot, but if you look closely, you can see there is a black bar below the almost-black toolbar.

![Screenshot 2023-10-18 at 3 03 38 PM](https://github.com/Automattic/pocket-casts-android/assets/4656348/57728d16-8951-4af8-b8dc-0f78f74c12e7)

Also there are some linter errors. Running the spotlessApply gradle task should fix those.

2023-10-18 19:55 UTC, mchowning commented on modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HelpFragment.kt
> +            settings.useWideViewPort = true
I wasn't able to tell what difference this made on the Help & Feedback screen. Can help me understand why this is needed?

2023-10-18 19:55 UTC, mchowning commented on modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HelpFragment.kt
> +            settings.layoutAlgorithm = TEXT_AUTOSIZING
I wasn't able to tell what difference changing the layoutAlgorithm made. Can help me understand why we need to set this?

2023-12-26 08:24 UTC, neeldoshii commented
I am closing this PR as this code is not properly optimized. Fixing a small issue is creating 2-3 more issue.
I think it needs much better approach to tackle this the time I wrote that code I was very beginner.

2023-12-26 08:24 UTC, closed without merging