Whenever users switches from wifi to mobile data he will get notified…
Automattic/pocket-casts-android pull request #1447
Opened 2023-10-09 23:14 UTC by neeldoshii

Linked Issue#1374 

## Description

Whenever a user streams podcast on Mobile Data he/she will get a toast warning that its streaming on mobile data. 

## Testing Instructions

1. Turn on the setting to warn when streaming an episode.
2. Connect to wifi and a metered connection
3. Start streaming an episode
4. Disconnect from wifi
5. You will get a toast saying its connected to mobile data. (for log testing filter the log with Check Data Connectivity)

### Improvements 

Needs to be only called when the episode is playing, not when its paused/stopped xyz.

## Screenshots or Screencast 

## Checklist
- [ ] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [ ] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [ ] I have considered whether it makes sense to add tests for my changes
- [ ] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [ ] Any jetpack compose components I added or changed are covered by compose previews
 
#### I have tested any UI changes...

- [X] with different themes
- [ ] with a landscape orientation
- [X] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

2023-10-09 23:40 UTC, CookieyedCodes commented
Personally I also will say their should be a toggle in settings to not turn on this popup 🤔 😉 (maby advanced settings?), just to prevent pointless pausing/people who are allways on the edge 😉

2023-12-13 02:43 UTC, mchowning requested changes
Thanks so much for your contribution @neeldoshii ! We really appreciate all your contributions, and I'm very sorry it took so long to get this reviewed.

I left a few comments about the code, but at a higher level, I don't think this is the best way to address https://github.com/Automattic/pocket-casts-android/issues/1374. A toast message isn't likely to be noticed by most users since people often aren't looking at their phone when they listen to podcasts. It also would still feel like the "warn before streaming" setting isn't working as it should since it would have drastically different behavior depending on whether the playback began on the mobile network (pop-up with a warning that requires confirmation before continuing to stream) versus when playback switches to a mobile network (a toast message is shown with no confirmation needed to continue).

I think what we need is to stop playback and display a warning that requires confirmation before continuing (like we do when for someone who starts playback when connected to a mobile network when they have the stream warning setting turned on).

Because I think we need to take a different approach to this, my inclination is to close this PR. If you want to continue working on this, let's open another PR with a different approach. If you'd rather collaborate in this PR to get this to where it needs to be though, let me know, because we can certainly do that.

One other nice-to-have in the future would be to try to avoid reformatting code where you are not making changes. When there are a lot of code formatting changes, it makes it more difficult to find and review the lines that are being changed, and that helps the review process go more quickly.

Let me know how you'd like to close this PR or if you want to work on moving this PR forward. 

Thanks again for contributing to Pocket Casts!

2023-12-13 02:43 UTC, mchowning commented on modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerContainerFragment.kt
> +
Looks like there are some empty lines at the end of each of the when clauses. Can we remove those?

2023-12-13 02:43 UTC, mchowning commented on modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerContainerFragment.kt
> +        viewModel.checkNetworkType(requireContext())
I'm not sure that the `PlayerContainerFragment` is the right place for this functionality. It doesn't seem like whether we show this should be tied to this view. Instead, I would think we'd want to give the warning anytime playback is happening, so maybe `MainActivity` or `PocketCastsApplication` would make more sense.

2023-12-13 02:43 UTC, mchowning commented on modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerContainerFragment.kt
> +                    Toast.makeText(context, "Using Mobile Data", Toast.LENGTH_SHORT).show()
This is showing the text anytime the network type changes, even if playback is not currently happening, whereas [the linked issue](https://github.com/Automattic/pocket-casts-android/issues/1374) is just addressing the situation where someone is actively streaming an episode and they switch to mobile data and they don't get any warning even though they have turned on the setting for showing a warning when streaming mobile data. Basically, I think we only want to respond when the user has that setting turned on and the user is streaming an episode that is switching to use mobile data.

2023-12-13 02:43 UTC, mchowning commented on modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerContainerFragment.kt
> +                    Toast.makeText(context, "Using Mobile Data", Toast.LENGTH_SHORT).show()
For strings like this that are user facing, we need to use a string resource so that they get translated.

2023-12-19 20:54 UTC, mchowning commented
Since you're not working on this, I'm going to go ahead and pick this up this issue myself @neeldoshii. I think I've got an idea for how to handle this well. Thanks so much for opening this PR though because it helped give me an idea for how to approach this.

2023-12-19 20:54 UTC, closed without merging