Update Upgrade screen and Profile screen with Intro Offer
Automattic/pocket-casts-android pull request #1733
Opened 2024-01-23 17:42 UTC by mebarbosa

This is part of: #1728

## Description
This PR updates two screens with intro offer UI: Upgrade screen page and the Profile Page

## Testing
git apply [release.patch](https://github.com/Automattic/pocket-casts-android/files/13998087/release.patch)

### Update Plan screen

1. Run the app and login in with a free account that never had a subscription
2. Go to `Podcasts` tab
3. Click on folders

- [ ] You should see the `Subscribe to [Plus/Patron]` button
- [ ] You should see the plan price bellow the badge
- [ ] For the Plus offer you should the the half price and the recurring price (see screenshot section)

### Profile screen
1. Run the app and login in with a free account that never had a subscription
2. Go to `Profile` tab
- [ ] You should see the `Subscribe to [Plus/Patron]` button
- [ ] You should see the plan price bellow the badge
- [ ] For the Plus offer you should the the half price and the recurring price (see screenshot section)

## Screenshots or Screencast 
| Intro | Regular Plus | Intro 
|--------|--------|--------|
|<img src="https://github.com/Automattic/pocket-casts-android/assets/42220351/232ed2dd-c8da-459b-b1d1-9df03666ed35" height="500"> |<img src="https://github.com/Automattic/pocket-casts-android/assets/42220351/b5984c94-0523-4a81-b1ef-2097795bd1ba" height="500"> | <img src="https://github.com/Automattic/pocket-casts-android/assets/42220351/f4889a24-3a0f-44e9-8059-9daf9877d768" height="500">| 

## Checklist
- [ ] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [ ] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [ ] I have considered whether it makes sense to add tests for my changes
- [ ] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [ ] Any jetpack compose components I added or changed are covered by compose previews
 
#### I have tested any UI changes...

- [ ] with different themes
- [ ] with a landscape orientation
- [ ] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

2024-01-24 10:05 UTC, MiSikora requested changes
I can't review this PR. I can't apply patch.

```
❯ git apply ~/Downloads/release.patch
error: patch failed: modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt:35
error: modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt: patch does not apply
```

I don't see that the flag `INTRO_PLUS_OFFER_ENABLED` from the patch is used anywhere in the code. However, when I fix the patch issues and apply it the build fails due to Google Services and the package name.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugProdGoogleServices'.
> No matching client found for package name 'au.com.shiftyjelly.pocketcasts'
```

I've tried testing it with the actual release build, and I found two issues.

1. Theming is broken. Using the dark theme price is not visible.

| Yearly | Monthly |
| - | - |
| ![Screenshot_20240124-104200](https://github.com/Automattic/pocket-casts-android/assets/30936061/2de61bec-a291-4e26-9ce5-e89d7189486d) | ![Screenshot_20240124-104220](https://github.com/Automattic/pocket-casts-android/assets/30936061/ea7bc99d-950c-4801-a16a-8090e53f212e) |

2. I'm not able to seethe offers in the profile screen. It might have to do something with the flag not being used. But it's my guess.

And just to clarify about the second step. I should comment out this whole section and not just the 182nd line?

https://github.com/Automattic/pocket-casts-android/blob/1bd628c028d8b21990c0e1579f99691f2ebf2d88/modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt#L182-L187

2024-01-24 10:23 UTC, mebarbosa commented
> 1. ng is broken. Using the dark theme price is not visible

Thanks @MiSikora for the call outs! Could you try with this other patch? [new_patch.patch](https://github.com/Automattic/pocket-casts-android/files/14036750/new_patch.patch)

1. Nice catch! I will fix this theme issue.
2. Yes!
> And just to clarify about the second step. I should comment out this whole section and not just the 182nd line?

3 I forgot to add one more step to see the offer. Sorry about that! You can go to PlayStore -> Testing -> Internal Testing -> Testers -> Internal Pocket Casts -> Add your email (that one you are using to test it. Also you need to log in Play Store (emulador/device) with this account you added in testers

2024-01-25 10:32 UTC, ashiagr commented
It looks great!


1. I still see theming issues for a dark theme:

https://github.com/Automattic/pocket-casts-android/assets/1405144/8e5bd458-1644-4e00-a430-069374aecd17

2. I know work is still in progress but do we want to allow both free trial and this new offer in the upgrade bottom sheet on Profile screen?

2024-01-25 13:59 UTC, mebarbosa commented
I've just pushed the changes for your feedback @ashiagr !

2024-01-26 06:47 UTC, ashiagr commented
Thanks for the updates! They look good now. 

One last feedback, regarding this requirement: 
> Run the app and login in with a free account that never had a subscription

I can see the offer on a free account that earlier had a subscription. I think it is because the offer eligibility is developer-determined. I'll approve this PR as the scope of this PR seems to be only UI updates, feel free to address it in another PR.

2024-01-26 06:47 UTC, ashiagr approved these changes

2024-01-26 10:41 UTC, mebarbosa commented
> eligibility

@ashiagr Yes! I will address the user eligibility in the next PR. Thanks for reviewing it and all inputs!

2024-01-26 10:41 UTC, merged