Display progress when is filtering Podcasts by Category
Automattic/pocket-casts-android pull request #1981
Opened 2024-03-26 12:30 UTC by mebarbosa

## Description
- Display the existing progress bar when is filtering a category or when is loading the category list
- I also made a minor refactor: 61ecd428679dbb1d615c97a56d21d88f19f4815d and ac235f968c785c879181d15d4a33f81b5b493b27 which was only renames

## Testing Instructions
- Have the new discover redesign enabled in Beta features
- Sometimes it's difficult to notice the progress bar because it finishes loading quickly, but you should see the Discover progress bar when you tap on any category, especially if it takes more time to fetch data from the API.

## Screenshots or Screencast 
[Screen_recording_20240326_092149.webm](https://github.com/Automattic/pocket-casts-android/assets/42220351/ab22b263-63b6-428a-834e-4cdd90b2085a)

## Checklist
- [ ] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [ ] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [ ] I have considered whether it makes sense to add tests for my changes
- [ ] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [ ] Any jetpack compose components I added or changed are covered by compose previews
 
#### I have tested any UI changes...

- [ ] with different themes
- [ ] with a landscape orientation
- [ ] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

2024-03-26 12:31 UTC, dangermattic commented
<!--
  1 Error: Please add tests for class <co...
  0 Warnings
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>CategoryPillListAdapter</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-03-27 11:08 UTC, MiSikora requested changes
There is a bug where tapping on `All categories` show progress bar as well.

https://github.com/Automattic/pocket-casts-android/assets/30936061/c4a712c2-4fd6-49bc-bf12-3039cabd87dc

2024-03-27 11:14 UTC, mebarbosa commented
> c78628e

@MiSikora I put this progress to display when is loading the categories bottom sheet, but I don't it's necessary. 

I've just removed it -> [c78628e](https://github.com/Automattic/pocket-casts-android/pull/1981/commits/c78628e2ac1d20dc938298628d2a041107a463a4)

2024-03-27 11:25 UTC, MiSikora approved these changes

2024-03-27 11:49 UTC, merged