Revert playback speed label taps
Automattic/pocket-casts-android pull request #2439
Opened 2024-07-03 12:44 UTC by geekygecko

## Description

The recent change to add 5x playback speed changed the behaviour of tapping the speed label. We have received lots of negative user feedback, so until we figure out a better way, this will restore the original functionality. 

Fixes https://github.com/Automattic/pocket-casts-android/issues/2427

## Testing Instructions
1. Play an episode
2. Open the full screen player
3. Tap on the effects icon
4. Tap the + button to increase the speed to 1.2
5. Tap the speed label
6. ✅ Verify the speed returns to 1x
7. Tap the speed label
8. ✅ Verify the speed changes to 1.5x
9. Tap the speed label
8. ✅ Verify the speed changes to 2x 
Tap the speed label
8. ✅ Verify the speed changes to 1x 

## Screencast 

https://github.com/Automattic/pocket-casts-android/assets/308331/c52697a0-88a8-4965-b6a4-301eef0cd5c2

2024-07-03 12:45 UTC, dangermattic commented
<!--
  0 Errors
  0 Warnings
  1 Message: This PR is still a Draft: some...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-07-03 17:41 UTC, mebarbosa requested changes
Thanks for putting this PR! 

I've noticed that we still has support for `5x` speed from notification media center. Is it something we want to address on this PR? 

<img width="283" alt="image" src="https://github.com/Automattic/pocket-casts-android/assets/42220351/dc1d9b71-8bb4-4a87-b67c-c0c7fbe176b7">

2024-07-04 07:56 UTC, b-aaron commented
One suggestion I have for this is being able to long press the speed label to get back to 1x. This would fix the amount of presses needed to get back quickly.

2024-07-04 08:44 UTC, CookieyedCodes commented
Ya predicted this would likely be an issue,
Which is why I designed a dial ui & preset manager https://github.com/Automattic/pocket-casts-android/discussions/1452#discussioncomment-7422777

But agreed long press going back to 1x or global default is a good fix that would help while the UI is a bit more work in to work on I get that 🤔

2024-07-04 13:55 UTC, mebarbosa approved these changes
Looks good to me! Thanks for the change

2024-07-04 13:55 UTC, merged

2024-07-04 23:58 UTC, geekygecko commented
> One suggestion I have for this is being able to long press the speed label to get back to 1x.

Thanks for the suggestion, I do wonder if a long press is too hidden.

> Which is why I designed a dial ui & preset manager

I like that it's easy to switch between the playback speeds! I was wondering about having quick adjust buttons, but they might not work on narrow phones. 
-1, -0.5, -0.1, (reset, show current speed), +0.1, +0.5, +1

2024-07-05 07:11 UTC, CookieyedCodes commented
No bothers :)

Hidden yes but tbh better then nothing and it's not like your app dosen't have hidden - functionality -

Oh that's not a bad idea 🤔🤔, still wouldn't mind a speed preset manager tbh but that also wouldn't be toto bad as an in-between 

                     -- -.1 [1.0x] +.1 + ++

Hmmmmm if it's on a new line instead of numbers below a certain screen size you could do smaller symbols 🤔🤔,
I do agree beyond 3x+ should only be button tho until a potential diall UI could be done 🤔🤔 some analytics should be assed for your smallest android devices and I suppose watch os need to be considered too 🤔 

Got to love the the complexity of even buttons 😅

2024-07-05 07:18 UTC, CookieyedCodes commented
Another suggestion that might be easier actually 

Is 
-- - [1.0x] + ++
& Make the -- & ++ user customisable 🤔🤔

2024-07-11 15:38 UTC, MtndaleRedneck commented
An idea is a setting to be able to set custom speed change defaults, meaning there'll be like 5 buttons below the speed adjustment that you can assign various speeds to those buttons. I have a few speeds that I tend to use for podcasts and have no need for all the speeds in between. Also long pressing the speed button should revert it to 1x.