Migrate sharing to deep link module
Automattic/pocket-casts-android pull request #2471
Opened 2024-07-08 13:36 UTC by MiSikora

## Description

This PR migrates sharing deep linking to the new module. It also fixes a bug with incorrect link recognition.

I didn't update changelog yet because the changelog file isn't ready yet for `7.69`. I'll update it once we release new beta.

Closes #2405

## Testing Instructions

### Migration

Do regression tests of opening links in mobile app that are shared from web app and from mobile app.

### Bug fix

1. Play an episode.
2. Share the episode from current position.
3. Open the link using the app.
4. App should recognize episode and the playback timestamp.
5. Share clip link to the episode.
6. Open the link using the mobile app.
7. App should open embedded web view clip player.

## Checklist
- [ ] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [x] I have considered whether it makes sense to add tests for my changes
- [x] ~All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`~
- [x] ~Any jetpack compose components I added or changed are covered by compose previews~
- [x] ~I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.~

2024-07-08 13:38 UTC, dangermattic commented
<!--
  1 Error: This PR is tagged with <code>d...
  2 Warnings: Class <code>ShareLinkNativeAda...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">This PR is tagged with <code>do not merge</code> label(s).</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>ShareLinkNativeAdapter</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>ShareLinkAdapter</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-07-08 16:04 UTC, mebarbosa requested changes
I was able to open some links that I created using the app, but when I tap on `https://pca.st/episode/c510a66f-f9c0-45c8-bca2-8c0cc1d5f055?t=1327` from the reported issue I see this error. Is this expected? 

<img width="282" alt="image" src="https://github.com/Automattic/pocket-casts-android/assets/42220351/4fbc8c15-15f6-4a89-9211-80178956ba60">

2024-07-08 16:36 UTC, MiSikora commented
Does the link open in the debug app and not prod app? If yes, can you filter the logs by `DeepLinking` tag and share the logs?

2024-07-11 10:49 UTC, mebarbosa approved these changes
LGTM!

I was using the wrong variant 😅

2024-07-11 10:51 UTC, merged