Android Auto: Update the progress bar in the browse view
Automattic/pocket-casts-android pull request #2945
Opened 2024-09-27 23:53 UTC by geekygecko

## Description

An Automotive manufacturer asked if we could add the progress bar in the browse view. There is a [Google guide for this](https://developer.android.com/training/cars/media#browse-progress-bar).

## Testing Instructions
1. Start the Android Auto emulator. 
```
cd /Applications/android-sdk/extras/google/auto/
chmod +x ./desktop-head-unit
./desktop-head-unit --usb
```
2. 

## Screenshots

Before
<img width="912" alt="Screenshot 2024-09-28 at 9 16 58 AM" src="https://github.com/user-attachments/assets/9dfec3a5-f7e1-4bb1-9452-28b208dfc1d6">

After

<img width="912" alt="Screenshot 2024-09-28 at 9 15 07 AM" src="https://github.com/user-attachments/assets/db6388da-5414-4e40-b821-48867014f1e0">

## Checklist
- [ ] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [ ] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [ ] I have considered whether it makes sense to add tests for my changes
- [ ] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [ ] Any jetpack compose components I added or changed are covered by compose previews
- [ ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.
 
#### I have tested any UI changes...

- [ ] with different themes
- [ ] with a landscape orientation
- [ ] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

2024-09-27 23:54 UTC, dangermattic commented
<!--
  0 Errors
  0 Warnings
  1 Message: This PR is still a Draft: some...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-09-30 12:45 UTC, mebarbosa requested changes
Nice improvement! 

The code looks good, but I found an issue with the progress sync if I have the in progress episodes opened.

1. You can start listening some episodes to have the in progress list populated
2. Open the in progress episodes tab
3. Play some episode
4. Seek to the end
5. Back to in progress list
6. You will see the episode is not updated with the current progress. 


https://github.com/user-attachments/assets/294a68a8-0c7a-4c24-b51c-c78a57824401

I had to refresh the page to get the episode progress updated

2024-10-07 06:00 UTC, geekygecko commented
> The code looks good, but I found an issue with the progress sync if I have the in progress episodes opened.

I mentioned this in the pull request description as an existing issue, but I will take another look at a solution as I just tested Spotify, and they have it working. "You may need to go to one level higher in the menu and back again for the episode row to update. I don't believe there is a way to fix this in Android Auto or Automotive."

2024-10-07 12:12 UTC, mebarbosa approved these changes

2024-10-09 17:04 UTC, merged