Use playback speed and skipped chapters for remaining playback time
Automattic/pocket-casts-android pull request #2955
Opened 2024-09-30 09:20 UTC by MiSikora

## Description

This PR accounts for playback speed and skipped chapters when displaying remaining playback time. Affected UI is remaining time under the player's seek bar and remaining time under next chapter button.

Closes #2249

## Testing Instructions

1. Play an episode with chapters.
2. Open full screen player.
3. Notice that the remaining duration of the whole episode and of a chapter changes with the playback speed.
4. Notice that the remaining duration changes with the chapters selection.
5. Smoke test seeking behavior for audio and video episodes.

## Checklist
- [x] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [x] I have considered whether it makes sense to add tests for my changes
- [x] ~All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`~
- [x] ~Any jetpack compose components I added or changed are covered by compose previews~
- [x] ~I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.~

2024-09-30 09:21 UTC, dangermattic commented
<!--
  0 Errors
  1 Warning: This PR is assigned to the mil...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-android/milestone/65">7.74</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-09-30 09:59 UTC, MiSikora commented on CHANGELOG.md
> +        ([#2955](https://github.com/Automattic/pocket-casts-android/pull/2955))
I'll move this to `7.75` when the changelog is ready.

2024-10-02 11:52 UTC, mebarbosa requested changes
Nice improvement! 

The code looks good and all tests within now playing worked as expected, but I noticed a problem with seeking + notification media 

1. The remaining time is not synced with the remaining the is displayed in now playing. One simple scenario that I was able to reproduce this is: Don't change the playback speed, seek to some point and check the remaining time displayed in notification media
2. Another similar scenario was involving the playback speed. See this video:

https://github.com/user-attachments/assets/bc253fc9-aac2-4283-98c4-2ee10a0f12d5

2024-10-02 11:55 UTC, MiSikora commented
> check the remaining time displayed in notification media

Where is the remaining time displayed in the notification?

2024-10-02 14:23 UTC, CookieyedCodes commented
@MiSikora 
![IMG_20241002_152238.jpg](https://github.com/user-attachments/assets/65886726-154b-4117-bdef-2caee5dcda39)

Could we also have this time be adapted to all episodes playback fx?

2024-10-02 14:29 UTC, MiSikora commented
This is much more complex and out of scope here. Can you file it as a separate enhancement under GitHub issues?

2024-10-02 14:30 UTC, CookieyedCodes commented
Sure 😊

2024-10-04 11:29 UTC, mebarbosa commented
> > check the remaining time displayed in notification media
> 
> Where is the remaining time displayed on the notification?

@MiSikora The app is stopping the video record when I put the device in lock screen, but if you lock your phone and check the playback there you will see the remaining time. You can see this in the last second of the video.  Let me know if I can help you with this test
 
<img width="239" alt="image" src="https://github.com/user-attachments/assets/f3c13dbf-241b-4720-b9f0-18329623636d">

2024-10-07 06:49 UTC, MiSikora commented
The timestamp on the right is the total episode's length. Not the remaining time.

2024-10-07 12:11 UTC, mebarbosa approved these changes

2024-10-07 12:12 UTC, mebarbosa commented
> The time displayed on the right is the total episode's length. Not the remaining time.

@MiSikora Got it!!

2024-10-07 13:19 UTC, merged

2024-10-18 09:26 UTC, Capable-Tea-001 commented
This is horrible functionality as I can't chose which to use.

2024-10-18 10:08 UTC, MiSikora commented
@Capable-Tea-001 Thanks for the feedback. It will be added in the next version. PR is [here](https://github.com/Automattic/pocket-casts-android/pull/3044).

In the future can you please either create a GitHub issue instead of commenting on a PR? This way more people will see this and not only people involved in the PR.

2024-10-18 10:28 UTC, Capable-Tea-001 commented
Ah, well perfect!

Sent from Proton Mail Android

-------- Original Message --------
On 10/18/24 11:09, Michał Sikora  wrote:

> ***@***.***(https://github.com/Capable-Tea-001) Thanks for the feedback. It will be added in the next version. PR is [here](https://github.com/Automattic/pocket-casts-android/pull/3044).
>
> In the future can you please either create a GitHub issue instead of commenting on a PR? This way more people will see this and not only people involved in the PR.
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/Automattic/pocket-casts-android/pull/2955#issuecomment-2422075593), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/BIKKTF4IBQWDZZOVX7AINK3Z4DM45AVCNFSM6AAAAABPC2Y3EGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMRSGA3TKNJZGM).
> You are receiving this because you were mentioned.Message ID: ***@***.***>