Gravatar native Quick Editor
Automattic/pocket-casts-android pull request #3055
Opened 2024-10-21 11:14 UTC by hamorillo

## Description
With the new Gravatar SDK release, we can use the native Quick Editor (QE), which allows an easy avatar change without needing the browser (except for the OAuth authorization).

Currently, we are using the web version; this PR is replacing it with the native version included within the Gravatar SDK.

## Testing Instructions

1. Enable `GRAVATAR_NATIVE_QUICK_EDITOR` feature flag under Profile -> Settings -> Beta features
2. Tap on the Profile tab
3. Tap on `Change avatar`
4. Verify Gravatar OAuth flow is opened in the browser
5. Complete the OAuth flow
6. You should be back on the app, and the QE should show your avatars
7. Modify your avatar
8. Close the QE and verify the new avatar is already shown in your account
9. Tap on `Change avatar`
10. OAuth flow should be presented again
11. Modify/upload your avatar
12. Close the QE and verify the new avatar is already shown in your account
13. `Sign out` from PocketCast
14. Login again with the same account
15. Tap on the Profile tab
16. Tap on `Change avatar`
17. OAuth flow should be presented again
18. Return to PocketCast
19. Disable `GRAVATAR_NATIVE_QUICK_EDITOR` feature flag under Profile -> Settings -> Beta features
20. Tap on the Profile tab
21. Tap on `Change avatar`
22. Browser with the web QE should be opened (previous behavior)

## Screenshots or Screencast 

<img width="300" alt="image" src="https://github.com/user-attachments/assets/ef722b66-e48f-44a8-8835-2e905071df4b"><img width="300" alt="image" src="https://github.com/user-attachments/assets/cb6cf3d2-a826-4f1a-b690-c2e0bda068da">

## Checklist
- [ ] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [x] I have considered whether it makes sense to add tests for my changes
- [x] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [] Any jetpack compose components I added or changed are covered by compose previews
- [ ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.
 
#### I have tested any UI changes...

- [ ] with different themes
- [ ] with a landscape orientation
- [ ] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

2024-10-21 11:16 UTC, dangermattic commented
<!--
  0 Errors
  0 Warnings
  1 Message: This PR is still a Draft: some...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-11-29 09:35 UTC, MiSikora requested changes
The feature works as intended, but I have several reservations. Pocket Casts Android averages about **80 avatar changes per day**. This is a rather big SDK that adds a lot of dependencies. We use most of these, so it’s not an issue in itself, but some are quite heavy. Below is the TLDR of dependency changes:

```
New Dependencies
androidx.browser:browser:1.8.0
androidx.compose.material3.adaptive:adaptive:1.0.0
androidx.compose.material3.adaptive:adaptive-android:1.0.0
androidx.security:security-crypto:1.0.0
androidx.window.extensions.core:core:1.0.0
androidx.window:window-core:1.3.0
androidx.window:window-core-android:1.3.0
com.automattic:ucrop:2.2.10
com.caverock:androidsvg-aar:1.4
com.composables:core:1.15.0
com.composables:core-android:1.15.0
com.google.code.gson:gson:2.10.1
com.google.crypto.tink:tink-android:1.13.0
com.gravatar:gravatar:2.1.0
com.gravatar:gravatar-quickeditor:2.1.0
com.gravatar:gravatar-ui:2.1.0
com.squareup.moshi:moshi-kotlin:1.15.1
io.coil-kt:coil-svg:2.7.0
io.github.osipxd:encrypted-datastore:1.1.1-beta03
io.github.osipxd:encrypted-datastore-bom:1.1.1-beta03
io.github.osipxd:encrypted-datastore-preferences:1.1.1-beta03
io.github.osipxd:security-crypto-datastore:1.1.1-beta03
io.github.osipxd:security-crypto-datastore-preferences:1.1.1-beta03
org.jetbrains.kotlin:kotlin-reflect:1.8.22

Upgraded Dependencies
androidx.navigation:navigation-common:2.8.1, (changed from 2.7.7)
androidx.navigation:navigation-common-ktx:2.8.1, (changed from 2.7.7)
androidx.navigation:navigation-compose:2.8.1, (changed from 2.7.7)
androidx.navigation:navigation-fragment:2.8.1, (changed from 2.7.7)
androidx.navigation:navigation-fragment-ktx:2.8.1, (changed from 2.7.7)
androidx.navigation:navigation-runtime:2.8.1, (changed from 2.7.7)
androidx.navigation:navigation-runtime-ktx:2.8.1, (changed from 2.7.7)
androidx.navigation:navigation-ui:2.8.1, (changed from 2.7.7)
androidx.navigation:navigation-ui-ktx:2.8.1, (changed from 2.7.7)
androidx.transition:transition:1.5.0, (changed from 1.4.1)
androidx.window:window:1.3.0, (changed from 1.0.0)
com.google.android.material:material:1.12.0, (changed from 1.11.0)
```

### Size Changes

Our apps’ sizes before and after including this library when compiled for my Pixel 6 device:

| App           | Before (KB)  | After (KB)   |
|---------------|--------------|--------------|
| `:app`        | 27,813,470   | 28,576,659   |
| `:automotive` | 10,366,835   | 11,296,070   |
| `:wear`       | 10,661,617   | 11,575,328   |

I don’t mind the changes in `:app` too much, but the effects on `:wear` and `:automotive` aren’t great. Unfortunately, our project’s modularization prevents excluding Gravatar dependencies in their binaries when used as in this PR.

- The issue for `:automotive` is only size.
- For `:wear`, the consequences are far worse. We already face compatibility issues with Compose, Wear Compose, Horologist, and Kotlin, and this dependency further complicates things. The SDK bundles numerous Compose libraries. While I understand why Compose might have been used, it burdens consumers significantly. 

### Moshi-Kotlin Dependency

Why use the reflect variant of Moshi instead of generated adapters? The transitive `kotlin-reflect` dependency is **3 MB pre-minification**. Ideally, consider using GSON, as it’s already a transitive dependency of `security-crypto-datastore-preferences`. If not, please avoid `moshi-kotlin`.

### Theming Issues

The theming feels inconsistent. I recommend allowing consumers to:

1. Specify light/dark mode manually instead of relying solely on the OS.
2. Provide their own theme for better integration with their app.

For now, a simple light/dark toggle would suffice. Full theme customization would be a long-term improvement.

| Light on dark | Dark on light | Theme mismatch |
| - | - | - |
| ![ligh-on-dark](https://github.com/user-attachments/assets/b968fde2-1b06-4514-a67f-1555b9a080d5) | ![dark-on-light](https://github.com/user-attachments/assets/3617ca98-ba4f-4d2b-ba19-119a0281003b) | ![mismatch](https://github.com/user-attachments/assets/83837dbc-3932-476f-8f9b-7ea36551c554) |

### Usability Concerns

When tapping "Change Avatar," the browser opens automatically if the user isn’t signed into WordPress. This breaks the user’s flow. Instead, keep the user on the same screen and allow them to navigate to the browser via a "Log in" button.

| Video | Log in sheet |
| - | - |
| <video src="https://github.com/user-attachments/assets/b2f1a214-cab3-42b6-ae0c-60f4eec7c405"> | ![log-in](https://github.com/user-attachments/assets/a90402d0-cdf1-4965-be6d-6ab80d087a27) |


---

## Summary

1. **Justification**: Why add this SDK? The low traffic for avatar changes doesn’t seem to justify the complexity introduced by these dependencies. What are the tangible benefits?
2. **Exclusion for Wear/Automotive**: The SDK should not land in `:wear` or `:automotive` modules. Pocket Casts needs some restructuring before adding the SDK. Alternatively, use a solution like `:media-ffmpeg` and `:media-noop` modules to handle this.
3. **Drop Moshi-Kotlin**: Avoid the `kotlin-reflect` dependency that comes transitevely from `moshi-kotlin`.
4. **Theming**: Add basic dark/light mode customization. Long term, provide full theme customizability.
5. **Browser Navigation**: Do not open the browser automatically if the user isn’t signed in. Keep the user on the current screen and let them navigate intentionally.

2024-11-29 09:39 UTC, MiSikora commented
The Lint failure is unrelated to this PR. You can sync with `main` to make it gone.

2024-11-29 21:04 UTC, geekygecko commented
Would the Gravatar integration but better as a separate application? This will cause maintenance issues for the Pocket Casts app long term. Other apps that would like to to include this library are going to experience the same issues. Could the alternative be that we open a URL, and if the Gravatar app is installed, it could open this instead of the website?

2024-12-09 12:04 UTC, mebarbosa commented
<!-- REUSE_ID: 1e8877df-d18b-48d9-aa8a-08b45605ba45 -->

Version `7.79` has now entered code-freeze, so the milestone of this PR has been updated to `7.80`.

2024-12-12 08:58 UTC, hamorillo commented
I've just found out that we are holding off on this integration for now. As I was about to ask for a second review, I'll explain the changes for the sake of history.

- Gravatar SDK version has been updated to `2.2.0-rc1` (we haven't found any issue with the RC, so this PR would only require the bump to `2.2.0`.
With the new SDK, we solve the **Drop Moshi-Kotlin** and **Theming**. The QuickEditor bottom sheet is customized based on the light/dark attribute of the current PocketCast theme.

- About excluding the Gravatar SDK for Wear/Automotive. As you suggested, I've followed the `ffmpeg` approach. I've created two modules, `gravatar` and `gravatar-noop`. The first one contains the code and the dependencies with the Gravatar SDK, and it's injected only into the `App` build. The `noop` doesn't have dependencies and is injected in Wear/Automotive builds. _Gravatar SDK doesn't land in those builds right now._

The last SDK release did not address the `Browser Navigation` point. We are considering it, but I would say it is a lower priority than the previous ones. 

Said that. I'm moving this PR to a draft. Feel free to drop any comments or suggestions about the latest changes / Gravatar SDK. I'm looking forward to it. I'll keep updating this PR with your feedback. On the other hand, if you think the current state adds value to PocketCast and makes sense to merge it, please let me know.

2024-12-12 13:26 UTC, MiSikora reviewed
I haven't tested the code yet, as I'll wait until we clarify the integration status. However, after reviewing the code, I recommend redesigning the `GravatarService` to avoid relying on `AssistedInject` and to ensure it doesn't throw errors when `null` values are passed. A design like this could work:

```kotlin
interface GravatarService {
    fun registerLauncher(fragment: Fragment,  onAvatarSelected: () -> Unit): Launcher

    suspend fun logout(email: String)
    
    interface Launcher {
        fun launchQuickEditor(email: String, isLightTheme: Boolean)
        fun launchExternalQuickEditor(email: String)
    }
}

class GravatarSdkService : GravatarService {
    override fun registerLauncher(fragment: Fragment, onAvatarSelected: () -> Unit) = object : GravatarService.Launcher {
        private val nativeEditorLauncher = fragment.registerForActivityResult(GetQuickEditorResult()) { quickEditorResult ->
            when (quickEditorResult) {
                GravatarQuickEditorResult.AVATAR_SELECTED -> onAvatarSelected()
                GravatarQuickEditorResult.DISMISSED, null -> Unit
            }
        }
        private val externalEditorLauncher = fragment.registerForActivityResult(ActivityResultContracts.StartActivityForResult()) { _ ->
            onAvatarSelected()
        }

        override fun launchQuickEditor(email: String, isLightTheme: Boolean) {
            nativeEditorLauncher.launch(
                GravatarEditorActivityArguments(
                    gravatarQuickEditorParams = GravatarQuickEditorParams {
                        this.email = Email(email)
                        avatarPickerContentLayout = AvatarPickerContentLayout.Horizontal
                        uiMode = if (isLightTheme) GravatarUiMode.LIGHT else GravatarUiMode.DARK
                    },
                    authenticationMethod = AuthenticationMethod.OAuth(
                        OAuthParams {
                            clientId = GRAVATAR_APP_ID
                            redirectUri = Gravatar.GRAVATAR_QE_REDIRECT_URL
                        },
                    ),
                ),
            )
        }

        override fun launchExternalQuickEditor(email: String) {
            externalEditorLauncher.launch(Intent(Intent.ACTION_VIEW, Uri.parse(Gravatar.getGravatarChangeAvatarUrl(email))))
        }
    }

    override suspend fun logout(email: String) = withContext(Dispatchers.IO) {
        GravatarQuickEditor.logout(email = Email(email))
    }
}

class NoOpGravatarServvice : GravatarService {
    override fun registerLauncher(fragment: Fragment, onAvatarSelected: () -> Unit) = object : GravatarService.Launcher {
        override fun launchQuickEditor(email: String, isLightTheme: Boolean) = Unit

        override fun launchExternalQuickEditor(email: String) = Unit
    }

    override suspend fun logout(email: String) = Unit
}
```

---

There’s also a broader point that requires discussion, either here or in a call. I mentioned it earlier:

> **Justification**: Why add this SDK? The low traffic for avatar changes doesn’t seem to justify the complexity introduced by these dependencies. What are the tangible benefits?

I’d still like to understand the benefits. I wouldn’t mind adding the SDK if it were a lightweight library. However, this SDK essentially behaves as a mini-application with many dependencies, which could lead to long-term maintenance issues for us. I'm especially concerned about presence of Compose in it.

2024-12-16 11:17 UTC, dangermattic commented
<!--
  0 Errors
  0 Warnings
  1 Message: This PR is still a Draft: some...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2025-01-06 10:31 UTC, geekygecko commented
<!-- REUSE_ID: 4c455df6-374d-4d06-b965-662068981aeb -->

Version `7.80` has now entered code-freeze, so the milestone of this PR has been updated to `7.81`.

2025-01-20 08:11 UTC, MiSikora commented
<!-- REUSE_ID: 931fc92a-aa6c-4e61-b158-82ca5ed5b42b -->

Version `7.81` has now entered code-freeze, so the milestone of this PR has been updated to `7.82`.

2025-03-14 09:59 UTC, MiSikora commented
I'll close this PR since at the moment we won't be moving forward with this.

2025-03-14 09:59 UTC, closed without merging