Fix: Disabled global Auto download new episodes setting overrides podcast specifc one
Automattic/pocket-casts-android pull request #3342
Opened 2024-12-09 16:19 UTC by mebarbosa

## Description
- Auto download screen was updating podcast auto download setting when this screen was opened

Fixes #3338

## Testing Instructions
- Follow the steps from https://github.com/Automattic/pocket-casts-android/issues/3338 to make sure the issue was fixed

## Screenshots or Screencast 
[Screen_recording_20241209_130121.webm](https://github.com/user-attachments/assets/b6b802ff-1b32-4336-a6ff-da5ffc66c530)

## Checklist
- [ ] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [ ] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [ ] I have considered whether it makes sense to add tests for my changes
- [ ] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [ ] Any jetpack compose components I added or changed are covered by compose previews
- [ ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.
 
#### I have tested any UI changes...

- [ ] with different themes
- [ ] with a landscape orientation
- [ ] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

2024-12-09 16:22 UTC, mebarbosa commented on modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoDownloadSettingsFragment.kt
> +            )
I put this code back to fix this issue. https://github.com/Automattic/pocket-casts-android/pull/3020/files

2024-12-10 11:30 UTC, MiSikora requested changes
App crashes when I execute this test:

1. Navigate to the **Profile** tab.  
2. Open **Settings**.  
3. Go to the **Auto Download** section.  
4. Ensure the **New Episodes** toggle is off.  
5. Navigate to the settings of any followed podcast.  
6. Disable the **Auto Download** setting.  
7. Tap on the **Podcasts** tab.  
8. Select any podcast.  
9. Open its settings.  
10. Enable the **Auto Download** setting.  
11. Navigate to the **Profile** tab.
12. 💥 

```
java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling androidx.recyclerview.widget.RecyclerView{626f1d9 VFED.V... ......ID 0,0-1080,1915 #7f0a04b4 app:id/recycler_view}, adapter:androidx.preference.PreferenceGroupAdapter@82d989f, layout:androidx.recyclerview.widget.LinearLayoutManager@5703faa, context:dagger.hilt.android.internal.managers.ViewComponentManager$FragmentContextWrapper@83664c3
	at androidx.recyclerview.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:3482)
	at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeChanged(RecyclerView.java:6071)
	at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyItemRangeChanged(RecyclerView.java:13219)
	at androidx.recyclerview.widget.RecyclerView$Adapter.notifyItemChanged(RecyclerView.java:8136)
	at androidx.preference.PreferenceGroupAdapter.onPreferenceChange(PreferenceGroupAdapter.java:354)
	at androidx.preference.Preference.notifyChanged(Preference.java:1294)
	at androidx.preference.TwoStatePreference.setChecked(TwoStatePreference.java:99)
	at au.com.shiftyjelly.pocketcasts.settings.AutoDownloadSettingsFragment.setupNewEpisodesToggleStatusCheck$lambda$33(AutoDownloadSettingsFragment.kt:425)
	at au.com.shiftyjelly.pocketcasts.settings.AutoDownloadSettingsFragment.$r8$lambda$U6792c7lbcG7qUaEN7BLPQFH6fM(Unknown Source:0)
	at au.com.shiftyjelly.pocketcasts.settings.AutoDownloadSettingsFragment$$ExternalSyntheticLambda11.invoke(D8$$SyntheticClass:0)
	at io.reactivex.rxkotlin.SubscribersKt$sam$io_reactivex_functions_Consumer$0.accept(Unknown Source:2)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.onSuccess(SingleSubscribeOn.java:68)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:56)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```

2024-12-11 08:01 UTC, MiSikora approved these changes
The change looks good. Would you mind adding a bug fix entry to the changelog?

> For some reason, I could not reproduce this issue you found using the emulator, which does not make any sense.

I don't understand it as well. It crashes when I test it on an emulator when I test with the previous commit.

2024-12-11 10:09 UTC, mebarbosa commented
> The change looks good. Would you mind adding a bug fix entry to the changelog?
> 
> > For some reason, I could not reproduce this issue you found using the emulator, which does not make any sense.
> 
> I don't understand it as well. It crashes when I test it on an emulator when I test with the previous commit.

@MiSikora I bet I am have some super weird cash problem in my Android Studio. It's not the first time this happens.  When you described these steps, I followed it and I could not reproduce, I repeated again and could not reproduce either. So I moved to other task that I had to use the real emulator. After that, I tried to reproduce this issue with the real device that I was using and finally I could reproduce the issue

2024-12-11 10:32 UTC, merged