Update release toolkit to 8.0+
Automattic/pocket-casts-android pull request #965
Opened 2023-05-15 15:36 UTC by mchowning

## Description
The mobile release toolkit has a new major version release, so this is attempting to update our app to use the release toolkit for 8.0+ following [the migration directions](https://github.com/wordpress-mobile/release-toolkit/blob/trunk/MIGRATION.md). 

One thing I'm unsure about is whether we should be pushing tags. It looks like WPAndroid [is not pushing them](https://github.com/wordpress-mobile/WordPress-Android/commit/ba8c70b304f0ecfb21f8b6baa5040ed9aca9c60e). 

## Testing Instructions
I'm not sure how to test this short of doing a release.

## Checklist
- [X] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [X] I have considered whether it makes sense to add tests for my changes

2023-05-15 20:24 UTC, oguzkocer requested changes
@mchowning Thank you for handling this update!

I think it's best to avoid pushing tags during `push_to_git_remote`. We are not interested in the local tags and if a developer intentionally avoided pushing a tag, we don't want to push that without their explicit permission. So, I suggest changing `push_to_git_remote()` commands with `push_to_git_remote(tags: false)`. Having said that, this is a _suggestion_ and if you want to keep pushing the tag, I don't think it's a problem either. `fastlane` decided to push tags by default, so I guess there is an argument to be made for that as well 🤷 

There are a couple `push_to_git_remote` calls that shouldn't be necessary. We only need to push to remote if we make any changes to the project. I've left comments about the commands that I thought wasn't necessary.

I think we should also push to remote in `code_freeze` lane before we call `setbranchprotection`. Without this, the lane will fail because GitHub will say that the `release` branch we are trying to add branch protection to does not exist.

You could also consider pushing to remote in `new_hotfix_release` lane because we are bumping the version number. However, you could also leave the decision to push to remote to the developer, so this is more of a personal preference. [We do this in WPAndroid](https://github.com/wordpress-mobile/WordPress-Android/blob/97ddc03839d2fb423d38662a1c9293773680a405/fastlane/lanes/release.rb#L127), because we'll handle the releases in CI and have to push everything to remote.

I hope you found this useful. Let me know if you have any questions/concerns.

2023-05-15 20:24 UTC, oguzkocer commented on fastlane/Fastfile
> +    push_to_git_remote()
```suggestion
```

This is not necessary since we are not changing anything in the project before this point.

2023-05-15 20:24 UTC, oguzkocer commented on fastlane/Fastfile
> +    push_to_git_remote()
```suggestion
```

This shouldn't be necessary either since `android_completecodefreeze_prechecks` is not making any changes to the project.

2023-05-17 16:04 UTC, mchowning commented
Thanks for the feedback @oguzkocer ! 🙇  I've adopted all of your proposed changes.

One question I had while looking at this more closely is how the `setfrozentag` call works. I noticed that we call that _after_ the `push_to_git_remote` call in the `code_freeze` lane. We also call  it in the `finalize_release` lane _before_ `push_to_git_remote`, but I wanted to make sure that isn't a tag that needs to be pushed to git.

2023-05-18 05:40 UTC, oguzkocer approved these changes
@mchowning Looks great! Thanks again for handling this update. Hopefully the next release cycle will go without a hitch, but please feel free to reach out if you come across any issues.

> One question I had while looking at this more closely is how the `setfrozentag` call works. I noticed that we call that _after_ the `push_to_git_remote` call in the `code_freeze` lane. We also call  it in the `finalize_release` lane _before_ `push_to_git_remote`, but I wanted to make sure that isn't a tag that needs to be pushed to git.

Yeah, this one is quite confusing because of poor naming. The [`setfrozentag`](https://github.com/wordpress-mobile/release-toolkit/blob/trunk/lib/fastlane/plugin/wpmreleasetoolkit/actions/common/setfrozentag_action.rb) lane updates the milestone, so it's unrelated to any git tags 😓 It's something we should change.

As far as I know we don't deal with git tags at all within our release lanes. We used to create the tag, but now we only create the GitHub release as a draft and the tag is created when we publish the release. So, we shouldn't be dealing with git tags at all.

2023-05-18 06:01 UTC, ashiagr approved these changes

2023-05-18 06:02 UTC, merged