translation fix
Automattic/pocket-casts-android pull request #986
Opened 2023-05-21 11:19 UTC by apollo2k4

## Description
removing html tags from <string name="podcasts_unarchive">

## Testing Instructions

## Screenshots or Screencast 
[](https://i.imgur.com/TeQ2jED.jpg)

## Checklist
- [-] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [-] I have considered whether it makes sense to add tests for my changes
- [+] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [-] Any jetpack compose components I added or changed are covered by compose previews

2023-05-21 11:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Automattic/pocket-casts-android?pullRequest=986) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Automattic/pocket-casts-android?pullRequest=986) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Automattic/pocket-casts-android?pullRequest=986) it.</sub>

2023-05-25 23:11 UTC, vladd-g requested changes

2023-06-07 15:08 UTC, closed without merging

2024-01-06 11:58 UTC, sryze commented
I noticed the same bug just a couple of days ago.

How long does it usually take to validate a translation? It seems that someone suggsted a new translation (without the `&nbsp;`) back in June but is still in Waiting status.

2024-01-08 17:48 UTC, mchowning commented
> How long does it usually take to validate a translation? It seems that someone suggsted a new translation (without the &nbsp;) back in June but is still in Waiting status.

Thanks for raising this. 🙇  Those have been approved, and we're looking into why they were waiting for so long.